### ISSUE TITLE
Question about integration tests

### ISSUE THREAD

**Issue by sebastian-almarracin** [soulve-innovations/hospital-product-catalog-sebastian-almarracin#1]
Hi @jboliveira,

Could you explain what you mean with "Functionality shall be under integration test" ?
I've never done integration tests before and am unsure how it is supposed to work.

**Comment by jboliveira** [comment]
Integration tests evaluate your api/service/project components on a broader level than unit tests. Unit tests are used to test isolated software components, such as individual class methods. Integration tests confirm that two or more app components work together to produce an expected result, possibly including every component required to fully process a request.

Also for an integration test is expected to have the following steps:

- The SUT's web host is configured.
- A test server client is created to submit requests to the app.
- The Arrange test step is executed: The test app prepares a request.
- The Act test step is executed: The client submits the request and receives the response.
- The Assert test step is executed: The actual response is validated as a pass or fail based on an expected response.
- The process continues until all of the tests are executed.
- The test results are reported.

So for example, you could perform integration tests over your controller.
